CREATE TABLE "REPERCUSSAO" (
  "referencia" text NOT NULL,
  "idagente" text NOT NULL,
  "cod_familiar_fam" text NOT NULL,
  "NB" text NOT NULL,
  "cod_uc" text NOT NULL,
  "cd_ibge" text NOT NULL,
  "data_atualizacao_fam" timestamp,
  "vlr_renda_percapita_fam" double,
  "vlr_renda_total_fam" double,
  "cod_familia_indigena_fam" text NOT NULL,
  "ind_familia_quilombola_fam" text NOT NULL,
  "cd_ibge_bpc" text NOT NULL,
  "especie" text NOT NULL,
  "situacao" text NOT NULL,
  "cd_ibge_dist" text NOT NULL,
  "subclasse" text NOT NULL,
  "usa_aparelho" text NOT NULL,
  "grupo" text NOT NULL,
  "motivo_validacao" text NOT NULL,
  "data_inicio_mensagem" timestamp,
  "data_limite_atualizacao" timestamp,
  "estado_cadastral" text NOT NULL,
  "CONTRATO" text NOT NULL,
  "CONTA_CONTRATO" text NOT NULL,
  "STATUS" text NOT NULL,
  "ACAO" text NOT NULL
);
